server:
  port: 9004
spring:
  application:
    name: project-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true